version: '3.9'
services:
  # node-frontend:
  #   container_name: frontend
  #   build: ./Frontend
  #   ports:
  #     - "5173:5173"

  # node-server:
  #   container_name: node-server
  #   build: ./line-oa-backend  # หรือเปลี่ยน path ให้ถูกต้องถ้าไฟล์ Dockerfile อยู่ที่อื่น
  #   ports:
  #     - "8000:8000"
  #   depends_on:
  #     - db
  #   networks:
  #     - app-network

  db:
    image: mysql:latest
    container_name: db
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: Linebot
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - app-network

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    container_name: phpmyadmin
    environment:
      PMA_HOST: db
      PMA_PORT: 3306
      PMA_USER: root
      PMA_PASSWORD: root
    ports:
      - "8080:80"
    depends_on:
      - db
    networks:
      - app-network

volumes:
  db_data:

networks:
  app-network:
    driver: bridge
