version: '3.9'
services:
  # node-frontend:
  #   container_name: frontend
  #   build: ./Frontend
  #   ports:
  #     - "3000:3000"

  # node-server:
  #   container_name: node-server
  #   build: ./line-oa-backend  # หรือเปลี่ยน path ให้ถูกต้องถ้าไฟล์ Dockerfile อยู่ที่อื่น
  #   ports:
  #     - "8000:8000"
  #   depends_on:
  #     db:
  #       condition: service_healthy

  db:
    image: mysql:latest
    container_name: db
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
    # healthcheck:
    #   test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
    #   interval: 5s
    #   timeout: 3s
    #   retries: 10
    env_file:
      - ../.env
    
  # ngrok:
  #   image: ngrok/ngrok:latest
  #   restart: unless-stopped
  #   command: ["http", "host.docker.internal:8000"]
  #   ports:
  #     - 4040:4040
  #   environment:
  #     - NGROK_AUTHTOKEN=2s8BIyiYJnArWzNJMmKvGlMstH8_3BzSYfuSVbz1RH932wyTe
  #   depends_on:
  #     - node-server
    

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    container_name: phpmyadmin
    environment:
      PMA_HOST: db
      PMA_PORT: 3306
      PMA_USER: ${PMA_USER}
      PMA_PASSWORD: ${PMA_PASSWORD}
    ports:
      - "8080:80"
    depends_on:
      - db
    

volumes:
  db_data:
